### ISSUE TITLE
Wrong plugin name

### ISSUE THREAD

**Issue by Thetortuga** [HappyValleyIO/kong-http-to-https-redirect#1]
Hi,
I installed your plugin, but it appears that it still have old name, "aliyun-http-filter".

However, it works fine ! Thanks for the job

**Comment by Thetortuga** [comment]
@stepbeekio Any update on this ?

**Comment by cristichiru** [comment]
Indeed, the name could be changed from aliyun-http-filter to kong-http-to-https-redirect

**Comment by stepbeekio** [comment]
Sorry for the delay - merged now.
