### ISSUE TITLE
Redirect not working when behind load balancer

### ISSUE THREAD

**Issue by Rhadros** [HappyValleyIO/kong-http-to-https-redirect#4]
If Kong is behind a load balancer a check for https is not working because it's always off. You should additionally check for the header value in X-Forwarded-Proto. If not "https" then you should redirect.
This should work behind a load balancer (at least it works on Heroku):

    function HttpFilterHandler:access(conf)
      HttpFilterHandler.super.access(self)

      if ngx.var.https ~= "on" and ngx.var.http_x_forwarded_proto ~= "https" then
        return ngx.redirect("https://" .. ngx.var.host .. ngx.var.request_uri, ngx.HTTP_MOVED_PERMANENTLY)
      end
    end

**Comment by dsteinkopf** [comment]
see PR #5 . This also is fixed in my repo dsteinkopf/kong-http-to-https-redirect#1 (please use branch `repo-dsteinkopf` -> https://github.com/dsteinkopf/kong-http-to-https-redirect/tree/repo-dsteinkopf)

**Comment by Rhadros** [comment]
Sorry for the long delay, but looks the same like my solution. I will close this one, because #5 has more features included
